#!/bin/bash

[[ "$1" == "" ]] && echo "Missing module name"

NAME=$1
PWD=$(pwd)

SOURCE="${BASH_SOURCE[0]}"
THIS="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$THIS/$SOURCE"
    THIS="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
THIS="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

mkdir -p ${NAME} && cd ${NAME}

cp ${THIS}/templates/{index.js,README.md,package.json,.travis.yml} .
cp ${THIS}/templates/gitignore .gitignore
mkdir -p test && cp ${THIS}/templates/test/index.js test/index.js

npm i standard tape -D

sed -i s/__NAME__/${NAME}/g index.js README.md package.json test/index.js

git init
git add .
git ci -m ':seedling: initial commit'
